server:
  port: 8003

spring:
  application:
    name: resttemplate-sample

logging:
  level:
    com.lzhpo: debug
  tracer:
    proxy-headers:
      - Authorization
      - User-Id
      - Country-Code
    pattern: '%5p [${spring.application.name},%X{X-B3-Parent-SpanName},%X{X-B3-TraceId},%X{X-B3-SpanId}]'

