server:
  port: 8002

spring:
  application:
    name: okhttp-sample

logging:
  tracer:
    proxy-headers:
      - Authorization
      - User-Id
    pattern: '%5p [${spring.application.name},%X{X-B3-Parent-SpanName},%X{X-B3-TraceId},%X{X-B3-SpanId}]'
