server:
  port: 8000

spring:
  application:
    name: logging-trace-service-sample

logging:
  trace:
    headers:
      - X-B3-TraceId
      - X-B3-SpanId
      - X-B3-SpanName
      - X-B3-Parent-SpanName