server:
  port: 8000

spring:
  application:
    name: feign-sample

logging:
  level:
    com.lzhpo: debug
#  pattern:
#    level: '%5p [${spring.application.name},%X{X-B3-Parent-SpanName},%X{X-B3-TraceId},%X{X-B3-SpanId}]'
  tracer:
#    enabled: false
    proxy-headers:
      - Authorization
      - User-Id
    pattern: '%5p [${spring.application.name},%X{X-B3-Parent-SpanName},%X{X-B3-TraceId},%X{X-B3-SpanId}]'

