server:
  port: 9001

spring:
  application:
    name: @artifactId@

logging:
#  pattern:
#    level: '%5p [${spring.application.name},%X{X-B3-Parent-SpanName},%X{X-B3-TraceId},%X{X-B3-SpanId}]'
  trace:
#    enabled: false
    proxy-headers:
      - Authorization
      - User-Id
