server:
  port: 6001

logging:
  level:
    com.lzhpo: debug

spring:
  application:
    name: dubbo-consumer-sample

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: nacos